# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20160202_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'FREE'), (1, 'ASSIGNED'), (2, 'OPEN'), (3, 'CLOSED'), (4, 'CANCELED'), (5, 'FAILED'), (6, 'INTERRUPTED'), (7, 'TIMEOUT'), (8, 'CREATED')], default=0, help_text='Current task state.'),
        ),
    ]
