# Generated by Django 3.2.20 on 2023-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20160202_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='retention_applied',
            field=models.BooleanField(default=False, help_text='Field to determine if the retention policy has been applied to the log results of this task.'),
        ),
    ]
